version: "3.1"
services:
  mongo6:
    profiles:
      - dev
    build:
      context: ./mongodb_rs
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27018
      # Use "mongo" instead of "mongosh" before v5.0
      MONGO_COMMAND: "mongosh"
    ports:
      - "27018:27018"
    restart: always
  web_prod:
    profiles:
      - prod
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    ports:
      - "3000:3000"
  web_dev:
    profiles:
      - dev
    restart: always
    environment:
      - MONGODB_URL=mongodb://localhost:27018/PulseCare
      # For WSL: https://www.reddit.com/r/nextjs/comments/1638ec6/comment/jy1h8ys/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
      - WATCHPACK_POLLING=true
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - "3000:3000"
      # This port to test `pnpm run dev` from within the container
      - "3001:3001"
    depends_on:
      - mongo6
    links:
      - mongo6
    # This is only for hot reload in development
    volumes:
      - ../:/pulsecare-webapp
      - /pulsecare-webapp/node_modules
      - /pulsecare-webapp/.next
