version: "3.1"
name: pulsecare-webapp
services:
  mongo6:
    container_name: MongoDB_Cluster
    profiles:
      - local
    build:
      context: ./mongodb_rs
      args:
        MONGO_VERSION: 6
    environment:
      # https://github.com/prisma/prisma/issues/11925
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27018
      # Use "mongo" instead of "mongosh" before v5.0
      MONGO_COMMAND: "mongosh"
    ports:
      - "27018:27018"
    restart: always
    # networks:
    #   - pulsecare-net

  web_prod:
    container_name: Pulsecare_Webapp-prod
    profiles:
      - prod
    restart: always

    build:
      args:
        - AUTH_SECRET=${AUTH_SECRET}
        - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
        - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
        - DATABASE_URL=${DATABASE_URL}
      context: ..
      dockerfile: docker/Dockerfile
      target: runner

    env_file:
      - ../.env.local
    ports:
      - "3000:3000"

  web_dev:
    container_name: Pulsecare_Webapp-dev
    profiles:
      - local
    restart: always
    environment:
      # README: https://github.com/prisma/prisma/discussions/23790#discussioncomment-9060992
      - DATABASE_URL=mongodb://mongo6:27018/pulsecare-web?replicaSet=rs0&retryWrites=true&w=majority&directConnection=true
      # For WSL: https://www.reddit.com/r/nextjs/comments/1638ec6/comment/jy1h8ys/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
      - WATCHPACK_POLLING=true
    env_file:
      - ../.env.local
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - mongo6
    links:
      - mongo6
    # networks:
    #   - pulsecare-net
    # This is only for hot reload in development
    volumes:
      - ../:/pulsecare-web
      - /pulsecare-web/node_modules
      - /pulsecare-web/.next
    # networks:
    #   - pulsecare-net
# networks:
#   pulsecare-net:
#     external: true
