---
- name: Install Docker on Debian
  hosts: all
  become: yes 

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker’s official GPG key
      ansible.builtin.shell:
        cmd: curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Set up the stable repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        create: yes

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Install Docker CLI and containerd
      apt:
        name:
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is enabled and running
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started
        
    - name: Download Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
        dest: "/usr/local/bin/docker-compose"
        mode: '0755'

    - name: Verify Docker Compose Installation
      ansible.builtin.command: docker-compose --version
      register: docker_compose_version
      changed_when: "'Docker Compose version' in docker_compose_version.stdout"

    - name: Ensure Docker service is enabled and running
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started
